name: Automation test scheduler 

on:
  schedule:
    - cron: 0 13 * * * # jam 13.00, cek di crontab guru
  workflow_dispatch:

jobs:
  automation-test:
    name: Automation test Ruby Capybara (pertemuan-6)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Capybara tests
        run: cucumber -t @search-google HEADLESS=yes PRIVATE=yes --publish --retry 5